<a href="https://colab.research.google.com/github/AlexCanoMoya/03MIAR---Algoritmos-de-Optimizacion/blob/main/SEMINARIO/Seminario_Alejandro_Cano_Moya_Algoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Alejandro Cano Moya  <br>
Url:

COLLAB: https://colab.research.google.com/drive/1O-5ccLaHqnQndjr-cJ42VD4re9uqGo1F?usp=sharing

GITHUB: https://github.com/AlexCanoMoya/03MIAR---Algoritmos-de-Optimizacion/tree/main/SEMINARIO
<br>

Problema:
# 1. Sesiones de doblaje <br>

## **Descripción del problema**:

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas.

Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día.

El objetivo es planificar las sesiones por día de manera que se gasto por los
servicios de los actores de doblaje sea el menor posible.

Los datos son:

Número de actores: 10

Número de tomas : 30

Actores/Tomas :

1 indica que el actor participa en la toma

0 en caso contrario

https://bit.ly/36D8IuK

(*) La respuesta es obligatoria<br>


## **Analisis inicial**
### Condiciones y restricciones
Hay 30 tomas en total y tenemos la restricción de que no se pueden superar 6 tomas por día.
Por tanto, el caso óptimo no puede ser inferior a **5 días de grabación**.

Al cobrar todos los actores lo mismo por día independientemente de número de tomas, podemos **ignorar el precio por actor**.  

El **orden de las tomas y de las sesiones es irrelevante** dentro de cada sesión, ya que no afecta al gasto final. 

### (*) ¿Cuantas posibilidades hay sin tener en cuenta las restricciones?

La **única restricción** que tenemos es el máximo de tomas por día.   

Si no tenemos en cuenta esta restricción, se pueden grabar todas las tomas en un mismo día, y en tener una sola y única sesión.     

Hay que grabar **30 tomas**. Como gracias a la magia de la post-producción, el orden de las grabaciones es indiferente, podemos definir el problema como una permutación sin repetición, por lo cual tendríamos $n! = 30! \approx 2.7e32 $ combinaciones posibles de tomas dentro de esta única sesión.

### ¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones?

Se define $n$ el número total de tomas y $m$ las tomas por sesión, con $n,k \in \mathbb{N}^2 $ y $1\leq k \leq n$        

Sabiendo que el orden de las grabaciones de las tomas es indiferente, elegimos $k$ veces una de las $n$ tomas para calcular el total de sesiones posibles, teniendo una menos por elegir en cada iteración.    
    
En una sesión tenemos $k$ tomas, que se pueden combinar de $k!$ maneras, por lo cual si ignoramos el orden de las tomas, tenemos una combinación sin repetición como **total de sesiones únicas**:

$$ s_{u}(n) = \frac{n!}{k! \cdot (n-k)!}$$    

Para calcular el total de soluciones, sabemos que la grabación necesitará realizar $\frac{n}{k}$ sesiones ($k \neq 0$).    
Sabemos también que el orden de las sesiones es irrelevante, y se pueden combinar de $\frac{n}{k}!$ maneras.        
Tenemos $s_{u}(n)$ sesiones por elegir para el primer día, pero las tomas no se han de repetir entre las diferentes sesiones, por lo cual tenemos $s_{u}(n-k)$ el segundo día, y así sucesivamente. Tenemos entonces, como **total de soluciones únicas posibles**:  

<br />

$$
 S = \frac{\prod_{i=0}^{ \frac{n}{k}-1} s_{u}(n-i \cdot k)}{\frac{n}{k}!}
 = \frac{1}{\frac{n}{k}!} \cdot \prod_{i=0}^{ \frac{n}{k}-1} \frac{(n-i \cdot k)!}{((n-i \cdot k) -k)! \cdot k!}
$$
      
<br /><br />
    
$$
\frac{1}{\frac{30}{6}!} *
\frac{30!}{(30-6)! \cdot 6!} *
\frac{24!}{(24 -6)! \cdot 6!} *
\frac{18!}{(18 -6)! \cdot 6!} *
\frac{12!}{(12 -6)! \cdot 6!} *
\frac{6!}{(6 -6)! \cdot 6!}
\approx 1,14 \cdot10^{16}
$$


### Modelo para el espacio de soluciones<br>
### (*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)

La mejor estructura de datos que podemos utilizar, en primera estancia, es un array de numeros. El id del array correspondera al id de la toma. Cada numero almacenado en el array representara una cadena binaria en la que el valor del bit x correspondera a la pertinencia del actor x en la toma.

Ejemplo de 5 tomas y 3 actores:
```
  Actores 0  1  2
0         1  1  1
1         0  0  1
2         0  1  0
3         1  1  0
4         0  1  0
```

Si usamos la librería pandas, con esto podemos sacar el número totales de actores que participan en cada toma o el número de tomas en las que participa un actor, permitiendo analizar las sesiones para optimizar los costos.

### Según el modelo para el espacio de soluciones<br>
### (*)¿Cual es la función objetivo?

La función objetivo se resume en calcular el coste de los actores para la grabación, que corresponde en sumar el coste de cada sesión, tras contabilizar cuántos actores son necesarios para cada una de ellas.

Para este problema, vamos a asignar un valor constante de 1 al precio que cada actor cobrará por presentarse a un día de grabación. De esta manera, podemos decir que el coste de cada día es la cantidad de actores necesarios en todas las tomas de dicho día. El coste total va a ser la suma total de los costos diarios.

La función objetivo es la que nos proporciona la cantidad de costo total de actores según las sesiones que se vayan a hacer con ellos. Debemos minimizar esta función.

A continuación la implementación de nuestra funcion objetivo:

In [ ]:
from google.colab import files
#### EJECUTAR Y CARGAR LA BASE DE DATOS ####
base_datos = files.upload()

Saving Datos problema doblaje(30 tomas, 10 actores).xlsx to Datos problema doblaje(30 tomas, 10 actores).xlsx


In [107]:
import io
import pandas as pd
import numpy as np

# Cargamos el dataframe
df = pd.read_excel(io.BytesIO(base_datos['Datos problema doblaje(30 tomas, 10 actores).xlsx']), skiprows=1)

# Nos quedamos solamente con lo que nos interesa del dataframe eliminando filas o columnas sin validez
df.rename({"Unnamed: 11":"a"}, axis="columns", inplace=True)
df.drop(["a"], axis=1, inplace=True)

df = df.drop(df.index[30])
df.reset_index(drop=True, inplace=True)

# Separamos los valores totales de la matriz de tomas/actor
total_act_toma = df['Total'].to_numpy()
total_tomas_act = df.iloc[-1].to_numpy()

total_act_toma = np.delete(total_act_toma, -1)
total_tomas_act = np.delete(total_tomas_act, (0, -1))

tomas = df["Toma"]
tomas_array = tomas.to_numpy()

# Dejamos las tomas del 0 al 29 (siendo 0 la toma 1 y 29 la 30)
tomas_array = np.delete(tomas_array, -1) - 1
tomas_list = tomas_array.tolist()

df = df.drop(df.index[30])
df.drop(["Total"], axis=1, inplace=True)
df.drop(["Toma"], axis=1, inplace=True)
df_array = df.to_numpy()

print(f"Actores/toma\n{df_array}")
print(f"Tomas {tomas_list}")
print(f"Total actores por toma {total_act_toma}")
print(f"Total tomas por actor {total_tomas_act}")

Actores/toma
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0

In [140]:
import numpy as np
import pandas as pd

def calculate_cost(solution : tuple, max_takes: int, actores_tomas : np.array) -> int:
  # Calculamos el número de sesiones que se necesitarán
  num_ses = len(solution)

  # Inicializamos costes a 0
  solution_cost = 0

  # Recorremos cada sesión
  for session in solution:
    
    takes_cnt = 0
    session_cost = 0

    # Sumamos las tomas de cada actor para ver si participa en alguna
    actores_tomas_session = actores_tomas[session]
    suma_actores = np.sum(actores_tomas_session, axis=0)

    # Si un actor ha participado en alguna toma de la sesión 
    # sumamos 1 al costo de la sesión
    for actor in range(0, len(suma_actores)):
      if suma_actores[actor] > 0:
        session_cost = session_cost + 1
    # Sumamos el costo de la sesión al total
    solution_cost = solution_cost + session_cost
      
  return solution_cost

In [111]:
# Ejemplo de funcionamiento con las tomas en orden
max_takes = 6
tomas_lista_ej = [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]]

calculate_cost(tomas_lista_ej, max_takes, df_array)

38

### (*)¿Es un problema de maximización o minimización?

El objetivo es reducir el coste y por tanto minimizar la función  $f(S)$. Por tanto, es un problema de minimización.

### Diseña un algoritmo para resolver el problema por fuerza bruta

Se diseña el algoritmo para resolver el problema por fuerza bruta pero se lanzará el script con un volumen de datos menor dado su gran coste computacional:

In [ ]:
def brute_force(actores_tomas : np.array, max_takes: int, takes) -> tuple:
    solutions = todas_las_combinaciones(max_takes, takes)

    best_solution = None
    best_solution_cost = None
    # Buscamos entre todas las soluciones para encontrar la de menor coste
    for solution in solutions:
        solution_cost = calculate_cost(solution, max_takes, actores_tomas)
        if best_solution is None or solution_cost < best_solution_cost:
            best_solution = solution
            best_solution_cost = solution_cost
    return best_solution_cost, best_solution

# Calculamos todas las posibles combinaciones de las tomas
def permutation(lst):
 
    if len(lst) == 0:
        return []
    if len(lst) == 1:
        return [lst]
    l = []
    
    for i in range(len(lst)):
       m = lst[i]
       remLst = lst[:i] + lst[i+1:]
       
       for p in permutation(remLst):
           l.append([m] + p)
    return l

def todas_las_combinaciones(max_takes, takes):
    takes_filt = []
    for p in permutation(takes):
        output=[p[i:i + max_takes] for i in range(0, len(p), max_takes)]
        for i in range(len(output)):
          output[i].sort()
        if output not in takes_filt:
          takes_filt.append(output)
    return takes_filt  

In [ ]:
# Ejemplo realizable para 6 tomas y 3 tomas por sesión
actores_tomas_ej = df_array[0:6]
max_takes_ej = 3
tomas_list_ej = tomas_list[0:6] 

brute_force(actores_tomas_ej, max_takes_ej, tomas_list_ej)

(11, [[0, 1, 5], [2, 3, 4]])

### Calcula la complejidad del algoritmo por fuerza bruta

Como el algoritmo por fuerza bruta genera todas las soluciones posibles,  $n!$  soluciones, tiene una complejidad  $O(n!)$

### (*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Lo primero a tener en cuenta es que lo ideal sería que en cada sesión, los actores que vayan puedan grabar el máximo de sus tomas totales, por lo que queremos conseguir es conseguir una lista de las tomas ordenadas por sesiones (de 6 en 6 tomas) empezando por las que más actores participan:

In [141]:
from operator import itemgetter
from heapq import nlargest
import random

# Aplicamos el algoritmo voraz
def alg_voraz(actores_tomas, max_takes, total_act_toma, intentos, iteracion = 0, best_result = 0, best_solution = 0):

    # Para la primera iteración
    if (iteracion == 0):
        # Hacemos una copia de la lista de actores por toma para que no se modifique
        total_act_toma_cpy = total_act_toma.copy()

        # Ordenamos solución que agrupa las sesiones por costes para tener una primera aproximación
        solution = ordenar_tomas(actores_tomas, max_takes, total_act_toma_cpy, False)
        # Calculamos los costes de la primera ordenación
        cost = calculate_cost(solution, max_takes, actores_tomas)

        # Al ser la primera iteración, será nuestra mejor solución por el momento
        best_result =  cost
        best_solution = solution

        iteracion += 1
        print(f"iteracion {iteracion}")
        print(f"Solucion parcial = {solution}")
        print(f"Coste parcial = {cost}")
        # Volvemos a iterar
        alg_voraz(actores_tomas, max_takes, total_act_toma, intentos, iteracion, best_result, best_solution)

    # En las siguientes iteraciones
    elif (iteracion < intentos):
        total_act_toma_cpy = total_act_toma.copy()

        # Mutamos la mejor solución hasta el momento para ver si conseguimos una mejor
        solution = mutation(best_solution, len(actores_tomas)/max_takes, max_takes)
        cost = calculate_cost(solution, max_takes, actores_tomas)

        iteracion += 1
        print(f"iteracion {iteracion}")
        print(f"Solucion parcial = {solution}")
        print(f"Coste parcial = {cost}")

        # Si hemos encontrado una solución con menos coste, la guardamos
        if cost < best_result:
          best_result = cost
          best_solution = solution
        print(f"Mejor Coste = {best_result},\nMejor Solution = {best_solution}")
        
        # Iteramos de nuevo
        alg_voraz(actores_tomas, max_takes, total_act_toma, intentos, iteracion, best_result, best_solution)

    # Cuando hayamos acabado las iteraciones, acabamos el programa
    else:
        return best_result, best_solution

# Función que ordenará las tomas según su participación de actores (de más a menos)
def ordenar_tomas(actores_tomas, max_takes, total_act_toma, mutation = False, lista_ordenada_tomas = [], session = 1):
    # Habrá tantas sesiones como tomas_totales/max_tomas_por_dia
    if (session <= int(len(actores_tomas)/max_takes)):
      lista_tomas = []
      # Cogemos los valores con mayor número de actores por toma
      largest = nlargest(max_takes, enumerate(total_act_toma), itemgetter(1))
      
      # Lo recorremos para quedarnos con el índice (la toma) y ponemos un 0 en su posición para que no
      # la tengamos en cuenta en su siguiente iteración
      for i in range(len(largest)):
        lista_tomas.append(largest[i][0])
        total_act_toma[largest[i][0]] = 0
      # Aumentamos sesión
      session += 1
      # Metemos la lista ordenada en la sublista final
      lista_ordenada_tomas.append(lista_tomas)
      # Volvemos a buscar los mayores valores para sacar las tomas sin contar esta vez con las que ya hemos sacado
      ordenar_tomas(actores_tomas, max_takes, total_act_toma, mutation, lista_ordenada_tomas, session)

    # Tras la última sesión, devolvemos la lista de listas de tomas ordenadas por costes
    return lista_ordenada_tomas

# Función que mutará nuestra mejor solución para encontrar una posible mejor solución
def mutation(solution, sessions, max_takes):
    # Elegimos dos números random sin repetición para intercambiar dos tomas y dos sesiones
    rand_sess = random.sample(range(int(sessions)), 2) 
    rand_toma = random.sample(range(max_takes), 2)
    
    # Hacemos el intercambio
    tmp = solution[rand_sess[0]][rand_toma[0]]
    solution[rand_sess[0]][rand_toma[0]] = solution[rand_sess[1]][rand_toma[1]]
    solution[rand_sess[1]][rand_toma[1]] = tmp

    return solution

In [116]:
%time final_solution = alg_voraz(df_array, max_takes, total_act_toma, 950)

iteracion 1
Solucion parcial = [[0, 10, 11, 3, 5, 6], [9, 19, 21, 24, 25, 1], [2, 4, 7, 8, 12, 13], [14, 28, 15, 16, 17, 18], [20, 22, 23, 26, 27, 29]]
Coste parcial = 38
iteracion 2
Solucion parcial = [[0, 10, 11, 3, 5, 6], [7, 19, 21, 24, 25, 1], [2, 4, 9, 8, 12, 13], [14, 28, 15, 16, 17, 18], [20, 22, 23, 26, 27, 29]]
Coste parcial = 39
Mejor Coste = 38,
Mejor Solution = [[0, 10, 11, 3, 5, 6], [7, 19, 21, 24, 25, 1], [2, 4, 9, 8, 12, 13], [14, 28, 15, 16, 17, 18], [20, 22, 23, 26, 27, 29]]
iteracion 3
Solucion parcial = [[21, 10, 11, 3, 5, 6], [7, 19, 0, 24, 25, 1], [2, 4, 9, 8, 12, 13], [14, 28, 15, 16, 17, 18], [20, 22, 23, 26, 27, 29]]
Coste parcial = 39
Mejor Coste = 38,
Mejor Solution = [[21, 10, 11, 3, 5, 6], [7, 19, 0, 24, 25, 1], [2, 4, 9, 8, 12, 13], [14, 28, 15, 16, 17, 18], [20, 22, 23, 26, 27, 29]]
iteracion 4
Solucion parcial = [[21, 10, 11, 3, 5, 6], [7, 19, 0, 24, 25, 1], [2, 4, 9, 8, 12, 13], [14, 28, 29, 16, 17, 18], [20, 22, 23, 26, 27, 15]]
Coste parcial = 39
Mejo

### Resultado final:
Mejor Coste = 32

Mejor Solution = [[17, 10, 27, 29, 2, 1], [13, 4, 0, 19, 11, 15], [6, 24, 28, 22, 18, 25], [12, 21, 8, 26, 20, 9], [23, 16, 5, 3, 7, 14]]

CPU times: user 1.41 s, sys: 258 ms, total: 1.67 s

Wall time: 1.52 s

### (*)Calcula la complejidad del algoritmo 

La complejidad de la función "ordenar_tomas" es la complejidad de "nlargest": $O(m * log(t))$ siendo m = máximo tomas por día y t el número de tomas totales, repitiéndose el número de sesiones (tomas totales/máximo tomas por día) por lo que se nos queda $O(m^2 * log(t))$.

La complejidad de la función "mutation" es de $O(1)$

La complejidad de la función final, "alg_vor" es $n$ (siendo $n$ el número de iteraciones) multiplicado por las dos funciones que aplican, por lo que la complejidad se nos queda:
    
**Complejidad algoritmo** = $O(n * n^2 * log(t) * 1)$ = $O(n^3*log(t))$ = $O(n^3)$


### Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

In [142]:
import random
import numpy as np

# Máximo de tomas para el juego de datos.
total_takes = random.randint(10, 50)

# Número máximo de sesiones.
max_takes = random.randint(3, int(total_takes / 3))

# Restricción de número de tomas por sesión.
session_takes = random.randint(2, int(total_takes / max_takes))

# Número de tomas.
takes = session_takes * max_takes

# Número de actores a tener en cuenta
n_actors = random.randint(4, 20)

# Probabilidad de actuar en una toma (25%)
p = 0.25 

# Generamos las participaciones de los actores por toma
actores_tomas = ()
for take_id in range(takes):
    take = []
    for actor in range(n_actors):
        take.append(int(random.random() < p))

    # Nos aseguramos tener al menos 1 actor por toma.
    if not sum(take):
        actor = random.randint(0, n_actors - 1)
        take[actor] = 1

    actores_tomas += (take,)

total_act_toma = np.zeros(shape=(len(actores_tomas)))

for i in range(len(actores_tomas)):
    total_act_toma[i] = sum(actores_tomas[i])

actores_tomas = np.array(actores_tomas)

print('Tomas totales:', takes)
print('Tomas máximas por sesión:', max_takes)
print('Total de actores:', n_actors)
print('Total actores por toma:', total_act_toma)
print('Actores_tomas:')
display(actores_tomas)

Tomas totales: 39
Tomas máximas por sesión: 13
Total de actores: 18
Total actores por toma: [4. 5. 3. 3. 3. 3. 5. 6. 1. 2. 4. 4. 6. 2. 2. 4. 5. 5. 5. 3. 5. 5. 2. 6.
 4. 5. 7. 3. 4. 2. 7. 4. 8. 6. 3. 7. 6. 7. 3.]
Actores_tomas:


array([[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

### Aplica el algoritmo al juego de datos generado

In [143]:
%time final_solution_2 = alg_voraz(actores_tomas, max_takes, total_act_toma, 950)

iteracion 1
Solucion parcial = [[32, 26, 30, 35, 37, 7, 12, 23, 33, 36, 1, 6, 16], [17, 18, 20, 21, 25, 0, 10, 11, 15, 24, 28, 31, 2], [3, 4, 5, 19, 27, 34, 38, 9, 13, 14, 22, 29, 8]]
Coste parcial = 54
iteracion 2
Solucion parcial = [[34, 26, 30, 35, 37, 7, 12, 23, 33, 36, 1, 6, 16], [17, 18, 20, 21, 25, 0, 10, 11, 15, 24, 28, 31, 2], [3, 4, 5, 19, 27, 32, 38, 9, 13, 14, 22, 29, 8]]
Coste parcial = 54
Mejor Coste = 54,
Mejor Solution = [[34, 26, 30, 35, 37, 7, 12, 23, 33, 36, 1, 6, 16], [17, 18, 20, 21, 25, 0, 10, 11, 15, 24, 28, 31, 2], [3, 4, 5, 19, 27, 32, 38, 9, 13, 14, 22, 29, 8]]
iteracion 3
Solucion parcial = [[34, 26, 30, 35, 37, 7, 12, 23, 33, 36, 1, 6, 16], [17, 18, 20, 21, 19, 0, 10, 11, 15, 24, 28, 31, 2], [3, 4, 5, 25, 27, 32, 38, 9, 13, 14, 22, 29, 8]]
Coste parcial = 53
Mejor Coste = 53,
Mejor Solution = [[34, 26, 30, 35, 37, 7, 12, 23, 33, 36, 1, 6, 16], [17, 18, 20, 21, 19, 0, 10, 11, 15, 24, 28, 31, 2], [3, 4, 5, 25, 27, 32, 38, 9, 13, 14, 22, 29, 8]]
iteracion 4
Sol

### Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y o variaciones al alza del tamaño

Ahora mismo, la solución es probabilística, pues para mejorar la solución, lo que hacemos es mutar la solución anterior y ver si mejora.

Estamos consiguiendo un algoritmo muy rápido pero no nos asegura la solución óptima, por lo que los siguientes pasos serían analizar qué toma es la menos óptima de la sesión y cambiarla por otra más óptima de otra sesión para mejorar el coste de esa sesión o para reducir los de las siguientes.

El algoritmo que hemos desarrollado se queda bastante abierto en cuanto a modificaciones del problema. Por un lado, no tenemos restricción en el código en cuanto a tomas, actores o número máximo de tomas por sesión, por lo que el algoritmo planteado sería buena base para adaptarlo a otros problemas que varíen condiciones, restricciones o dimensión del problema.